export const escape = s => String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
export const arrow = '<span aria-hidden="true">↗</span>';
export const button = (label, href, secondary=false) => `<a class="button ${secondary?'button-secondary':''}" href="${href}">${label}${arrow}</a>`;
export const links = [['About','/about/'],['Capabilities','/capabilities/'],['Our approach','/operations/'],['Suppliers','/suppliers/']];
export function header(path) { return `<a class="skip-link" href="#main">Skip to content</a><header class="header"><div class="container header-inner"><a class="wordmark" href="/" aria-label="SmooveOperator home">Smoove<span>Operator</span><b aria-hidden="true">.</b></a><button class="menu-toggle" aria-controls="main-navigation" aria-expanded="false" hidden>Menu <span aria-hidden="true">＋</span></button><nav id="main-navigation" aria-label="Main navigation">${links.map(([l,h])=>`<a href="${h}" ${path===h?'aria-current="page"':''}>${l}</a>`).join('')}${button('Work with us','/contact/',true)}</nav></div></header>`; }
export function footer() {return `<footer class="footer"><div class="container"><div class="footer-top"><div><a class="wordmark" href="/">Smoove<span>Operator</span><b aria-hidden="true">.</b></a><p>Commerce with intention.<br>Operations with discipline.</p></div><div class="footer-nav"><div><span class="eyebrow">Explore</span><a href="/">Home</a>${links.slice(0,3).map(([l,h])=>`<a href="${h}">${l}</a>`).join('')}</div><div><span class="eyebrow">Connect</span><a href="/suppliers/">Supplier relationships</a><a href="/contact/">Contact</a><a href="/privacy/">Privacy policy</a><a href="/terms/">Terms of use</a></div></div></div><div class="footer-bottom"><span>© ${new Date().getFullYear()} SmooveOperator</span><span>Commerce. Distribution. Marketplace operations.</span></div></div></footer>`;}
export const heading = (label,title,text='')=>`<div class="section-heading"><div><p class="eyebrow"><span class="tiny-line"></span>${label}</p><h2>${title}</h2></div>${text?`<p class="section-intro">${text}</p>`:''}</div>`;
export const pageHero = (label,title,description)=>`<section class="page-hero container"><p class="eyebrow"><span class="tiny-line"></span>${label}</p><h1>${title}</h1><p class="lead">${description}</p></section>`;
export const cta = ()=>`<section class="container cta-wrap"><div class="cta"><div><p class="eyebrow">Better commerce starts with a conversation</p><h2>Good products.<br><span class="muted">Shared possibilities.</span></h2></div><div><p>We’re seeking suppliers who value clear communication and a thoughtful approach to marketplace commerce.</p>${button('Start a conversation','/contact/?type=supplier')}</div></div></section>`;
export const icon = (name) => { const paths={source:'<circle cx="10" cy="10" r="6"/><path d="m15 15 6 6M7 10h6M10 7v6"/>',market:'<rect x="3" y="4" width="18" height="16" rx="2"/><path d="M3 9h18M8 14h3M8 17h8"/>',inventory:'<path d="m12 3 9 5-9 5-9-5 9-5Zm-9 5v10l9 5 9-5V8M12 13v10M7 5.8l9 5"/>',partner:'<path d="M9 8H6a4 4 0 0 0 0 8h5M15 8h3a4 4 0 0 1 0 8h-5M8 12h8"/>'};return `<svg class="icon" viewBox="0 0 24 26" fill="none" stroke="currentColor" stroke-width="1.3" aria-hidden="true">${paths[name]||paths.market}</svg>`;};
export const capabilities=[['01','market','Marketplace commerce','Bringing established products to online customers with careful listing and channel decisions.'],['02','source','Disciplined sourcing','Evaluating product fit, source documentation, demand, and the economics behind each purchase.'],['03','inventory','Inventory coordination','Planning the path from source to third-party preparation and marketplace fulfillment.'],['04','partner','Supplier relationships','Developing relationships with brands, wholesalers, and distributors for repeatable commerce.']];
export const cards=()=>`<div class="capability-grid">${capabilities.map(([n,i,t,d])=>`<article class="capability-card reveal"><div class="card-top">${icon(i)}<span class="index">${n}</span></div><h3>${t}</h3><p>${d}</p><a class="text-link" href="/capabilities/#capability-${n}">Explore capability ${arrow}<span class="sr-only">: ${t}</span></a></article>`).join('')}</div>`;
export const steps=[['Source','Retailers & suppliers','Product selection and purchasing'],['Prepare','Third-party prep','Inspection, labeling, and shipment preparation'],['Fulfill','Marketplace networks','Storage, order fulfillment, and delivery'],['Reach','The customer','Accurate listings and a reliable purchase experience']];
export const flow=()=>`<ol class="flow">${steps.map(([t,s,d],i)=>`<li><span class="step-number">0${i+1}</span><h3>${t}</h3><p class="flow-sub">${s}</p><p>${d}</p></li>`).join('')}</ol>`;
export const diagram=()=>`<div class="system-diagram" aria-label="Planned commerce model: products are sourced, prepared by third parties, and fulfilled through marketplaces to customers."><div class="diagram-top"><span class="eyebrow">The operating model</span><span class="diagram-label">SOURCE → CUSTOMER</span></div><div class="diagram-orbit orbit-one" aria-hidden="true"></div><div class="diagram-orbit orbit-two" aria-hidden="true"></div><div class="diagram-node node-source">${icon('source')}<div><span>01 / THE STARTING POINT</span><strong>Considered sourcing</strong></div></div><div class="diagram-connector connector-one" aria-hidden="true"></div><div class="diagram-node node-core"><span class="core-mark">S<span>O</span><b>.</b></span><div><strong>SmooveOperator</strong><span>SELECT · COORDINATE · REFINE</span></div></div><div class="diagram-connector connector-two" aria-hidden="true"></div><div class="diagram-node node-fulfill">${icon('inventory')}<div><span>02 / THE FULFILLMENT PATH</span><strong>Prep & marketplace networks</strong></div></div><div class="diagram-connector connector-three" aria-hidden="true"></div><div class="diagram-end"><span aria-hidden="true">↘</span>03 / EVERYDAY CUSTOMERS</div><div class="diagram-bottom"><span>Independent commerce</span><span>Connected by design</span></div></div>`;
export function contactForm(){return `<form name="business-inquiry" method="POST" action="/thank-you/" data-netlify="true" netlify-honeypot="bot-field" id="contact-form"><input type="hidden" name="form-name" value="business-inquiry"><p hidden><label>Leave this field empty <input name="bot-field" tabindex="-1" autocomplete="off"></label></p><div class="form-grid"><div><label for="name">Name <span>(required)</span></label><input id="name" name="name" autocomplete="name" required maxlength="120"></div><div><label for="company">Company</label><input id="company" name="company" autocomplete="organization" maxlength="160"></div><div><label for="email">Email <span>(required)</span></label><input id="email" name="email" type="email" autocomplete="email" required maxlength="254"></div><div><label for="phone">Phone <span>(optional)</span></label><input id="phone" name="phone" type="tel" autocomplete="tel" maxlength="40"></div></div><label for="inquiry">Inquiry type <span>(required)</span></label><select id="inquiry" name="inquiry" required><option value="">Select an inquiry type</option><option value="supplier">Supplier / Wholesale</option><option value="brand">Brand Partnership</option><option value="business">Business Inquiry</option><option value="general">General Contact</option></select><label for="message">How can we work together? <span>(required)</span></label><textarea id="message" name="message" rows="6" required minlength="10" maxlength="5000" aria-describedby="message-help"></textarea><p id="message-help" class="form-note">Share a little about your business and what you have in mind. Please leave out sensitive documents and financial information.</p><p class="form-note">We use these details to respond to your inquiry. Read our <a href="/privacy/">privacy policy</a>.</p><button class="button" type="submit">Send inquiry ${arrow}</button><p id="form-status" role="status" aria-live="polite" tabindex="-1"></p></form>`;}
